name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cd silk;make
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ !github.head_ref }}
      with:
        name: ${{ matrix.goos }}_${{ matrix.goarch }}
        path: ./
